version: '3.8'
services:
  movies:
    image: viswanathkasi/jmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: viswanathkasi/jtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: viswanathkasi/jdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: viswanathkasi/jrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
