version: '3.8'
services:
  movies:
    image: viswanathkasi/nmovies:latest
    ports:
      - "8081:8080"
    deploy:
      replicas: 3
  train:
    image: viswanathkasi/ntrain:latest
    ports:
      - "8082:8080"
    deploy:
      replicas: 3
  dth:
    image: viswanathkasi/ndth:latest
    ports:
      - "8083:8080"
    deploy:
      replicas: 3
  recharge:
    image: viswanathkasi/nrecharge:latest
    ports:
      - "8084:8080"
    deploy:
      replicas: 3
